#FROM python:3


#Install Rasa CORE
#RUN pip install rasa_core
#RUN pip install rasa_nlu

#ADD ./restaurantbot/dev-requirements.txt /
#ADD ./restaurantbot/requirements.txt /
#ADD ./restaurantbot/setup.py /
#ADD ./restaurantbot/version.py /rasa_core/
#ADD ./restaurantbot/README.md /
#RUN pip install -r dev-requirements.txt

#ADD ./restaurantbot /

#EXPOSE  5005
#CMD [ "python", "-m", "rasa_core.server", "-d","models/dialogue", "-u", "models/nlu/current", "-o", "out.log" ]
#CMD ["ls"]

